[env:digispark-tiny]
platform = atmelavr
board = digispark-tiny
framework = arduino

; If you have upload issues, sometimes you need to specify the protocol:
upload_protocol = micronucleus

lib_deps =
    soylentorange/DigiSpark_PWM @ ^1.0.0
