[env:digispark-tiny]
platform = atmelavr
board = digispark-tiny
framework = arduino
upload_protocol = micronucleus
debug_tool = simavr

; Build flags:
;   F_CPU=8000000L  -> confirms 8 MHz internal oscillator (no crystal)
;   -Os             -> optimize for size (ATtiny85 has 8KB flash)
build_flags =
    -Os
